version: '3.9'

services:
  elyon-postgres:
    image: postgres
    restart: always
    volumes:
        - "elyon-db:/var/lib/postgresql/data"
    ports:
        - "5432:5432"
    env_file:
      - .env

volumes:
  elyon-db:
    external: true
