services:
  heypal-postgres:
    image: postgres
    restart: always
    volumes:
        - "heypal-db:/var/lib/postgresql/data"
    ports:
        - "5437:5432"
    env_file:
      - .env

volumes:
  heypal-db:
    external: true
